version: "1.0"

networks:
  kafka-net:
    driver: bridge

services:
  db:
    container_name: h2-db
    image: oscarfonts/h2
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    restart: always

  zookeeper:
    image: bitnami/zookeeper:3.7
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  #TODO: kafka connect error 수리
  kafka:
    image: bitnami/kafka:3.1.2
    networks:
      - kafka-net
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  user-api:
    build: "./user-api"
    container_name: "sleep-well-user-api"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:test
      SPRING_DATASOURCE_USERNAME: sa
    depends_on:
      - db
      - zookeeper
      - kafka

  # TODO: kafka server 분리
  #  kafka-api:
  #    build: "./kafka"
  #    container_name : "sleep-well-kafka"
  #    ports :
  #      - "9000:9000"

  # TODO: batch server 분리
