iamport:
  api-key: ENC(qEHe1ovSqSwo37g2Td7oJ1S9JgFrvdAFwUB1tyYvPhI=)
  api-secret: ENC(5ynAhUPFenEmzIyAifZFZ9mZE5opzWHSlTzZL95pHmP/XLpasFkGjy06MDZh8HCa5el5LYSGZI/eam81PiMlpdrKIKKDSiWE8U9cdE/tDlaNp8ts2ER/NIsu9z/K52MK)

jwt:
  provider:
    token-validate-time: 600000
  filter:
    header: ACCESS_TOKEN
    prefix: Bearer

kafka:
  broker:
    port: localhost:9099

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace
server:
  port: 9090
