iamport:
  api-key: ENC(qEHe1ovSqSwo37g2Td7oJ1S9JgFrvdAFwUB1tyYvPhI=)
  api-secret: ENC(5ynAhUPFenEmzIyAifZFZ9mZE5opzWHSlTzZL95pHmP/XLpasFkGjy06MDZh8HCa5el5LYSGZI/eam81PiMlpdrKIKKDSiWE8U9cdE/tDlaNp8ts2ER/NIsu9z/K52MK)

jwt:
  provider:
    secret-key: Zi1sYWItdGlja2V0aW5nLXByb2plY3Qtc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1rZXktZi1sYWItdGlja2V0aW5nLXByb2plY3Qtc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1rZXkK
    token-validate-time: 6000
  filter:
    header: ACCESS_TOKEN
    prefix: Bearer
